### ISSUE TITLE
Funcitonal reactive state....

### ISSUE THREAD

**Issue by aaron-lebo** [arkverse/lell#1]
Is how the description of this repo reads. I really don't mean to be a pedant.

But if you have discovered funcitonal reactive state, it sounds impressive. ;)

Cool library!

**Comment by zaiddag** [comment]
Not quite sure what you mean xD

**Comment by theefer** [comment]
There is a typo in "functional". I was about to report it too.

**Comment by zaiddag** [comment]
oh lol
